sudo: required
dist: trusty
language: java
env:
 - SPRING_PROFILES_ACTIVE=local
jdk:
 - oraclejdk8
addons:
  chrome: stable
before_install:
  - cd zoo
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
